output = "example/boiler/models"
wipe = true
add-enum-types = true

[auto-columns]
created = "created_at"
updated = "updated_at"

[psql]
dbname = "postgres"
host = "localhost"
port = 5432
user = "user"
pass = "pass"
sslmode = "disable"